spring:
  application:
    name: eum-sso
  datasource:
    url: jdbc:postgresql://localhost:15432/eumdb
    username: eum
    password: 'qwer1234'
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
